---

- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    ios_banner:
      banner: login
      text: |
        Nikolay is cool!
      state: present

  - name: Add Loopback

    ios_interface:
      name: Loopback21
      state: present
